#!/usr/bin/env bash
#
# 00-testbuild.sh: see if an "svn co" of current directory followed by
# "make" produces the "ims" executable needed for cs154-2014 p5ims
#
set -o errexit
set -o nounset

tmpdir=""
function cleanup {
  # comment out the "rm -rf" line below if you want to preserve the
  # tmp directory created by this script, to inspect the files there
  # (generated by svn co)
  rm -rf $tmpdir
}
tmpdir=$(mktemp -d /tmp/cs154tmp.XXXXXXXX)
trap cleanup err exit int term  # remove tmpdir when done

# get svn URL for this directory
echo "=== svn info"
URL=$(svn info | grep URL | sed  s/^URL:\ //g)
echo "=== learned URL $URL"
if [[ ! $URL =~ ^https://phoenixforge.cs.uchicago.edu ]]; then
  echo "P5IMS ERROR: didn't get valid URL from svn info: (URL=$URL)" >&2
  exit 1
fi
if [[ ! $URL =~ /p5ims$ ]]; then
  echo "P5IMS ERROR: URL from svn info didn't end with p5ims: (URL=$URL)" >&2
  exit 1
fi

# go to tmpdir
echo "=== cd $tmpdir"
cd $tmpdir

# try an svn checkout
echo "=== svn co $URL"
svn co $URL

# then cd into p5ims
echo "=== cd p5ims"
cd p5ims

# and then make (script will exit if make fails)
echo "=== rm -f ims; make"
rm -f ims; make

# did make produce the executable we want?
if [[ ! -x ims ]]; then
  echo "P5IMS ERROR: make didn't produce an executable \"ims\"" >&2
  exit 1
fi

# should be the last line you see from this script
echo "P5IMS OK: build"
