
int absVal(int);
int test_absVal(int);
int addOK(int, int);
int test_addOK(int, int);
int allEvenBits();
int test_allEvenBits();
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int ezThreeFourths(int);
int test_ezThreeFourths(int);
int fitsBits(int, int);
int test_fitsBits(int, int);
int greatestBitPos(int);
int test_greatestBitPos(int);
int ilog2(int);
int test_ilog2(int);
int implication(int, int);
int test_implication(int, int);
int isPower2(int);
int test_isPower2(int);
int logicalNeg(int);
int test_logicalNeg(int);
int multFiveEighths(int);
int test_multFiveEighths(int);
int rotateLeft(int, int);
int test_rotateLeft(int, int);
int satAdd(int, int);
int test_satAdd(int, int);
int sm2tc(int);
int test_sm2tc(int);
int tc2sm(int);
int test_tc2sm(int);
int trueThreeFourths(int);
int test_trueThreeFourths(int);
int trueFiveEighths(int);
int test_trueFiveEighths(int);
